import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { MotionConfig } from "framer-motion";
import App from "../src/App";
import { ScenicBackground } from "../src/components/ScenicBackground";
import { useAuthStore } from "../src/store/useAuthStore";
import { useBooksStore } from "../src/store/useBooksStore";
import { useReaderStore } from "../src/store/useReaderStore";
import { useChatStore } from "../src/store/useChatStore";
import { useAppearanceStore } from "../src/store/useAppearanceStore";
import { useReadingPreferencesStore } from "../src/store/useReadingPreferencesStore";
import { measureReadingOffset, measureReadingPosition, restoreReadingOffset } from "../src/lib/reader-text-position";
import { fixtureUser, installReaderFixtures } from "./fixtures/reader-fixtures";
import "../src/index.css";
import "../src/theme/scenic-ui.css";
const fixture = installReaderFixtures();
useAuthStore.getState().signIn({ accessToken: "public-fixture-token", user: fixtureUser });
Object.assign(window, { readerAcceptance: { ...fixture, books: useBooksStore, reader: useReaderStore, chat: useChatStore, appearance: useAppearanceStore, preferences: useReadingPreferencesStore, measure: measureReadingOffset, measurePosition: measureReadingPosition, restore: restoreReadingOffset } });
createRoot(document.getElementById("root")!).render(<StrictMode><MotionConfig reducedMotion="user"><ScenicBackground /><App /></MotionConfig></StrictMode>);
